<div class="row">
    <div class="col-md-8">
        <form name="addData" method="post" id="addData" class="form" action="<?php echo $block->getBaseUrl().'assignment4_submitdetails/page/save';?>"
              data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>"
              data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset">
                <legend class="legend"><span>Contact Us - Details</span></legend>
                <fieldset class="fieldset row">
                    <div class="fields col-md-6">
                        <div class="field name required">
                            <label class="label" for="title"><span>Your Name</span></label>
                            <div class="control">
                                <input name="name" id="name" title="name" value="" class="input-text" type="text"
                                       data-validate="{required:true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title"><span>Email Address</span></label>
                            <div class="control">
                                <input name="email_address" id="email_address" title="email_address" value="" class="input-text" type="text"
                                       data-validate="{required:true}">
                            </div>
                        </div>
                        <div class="field name required">
                            <label class="label" for="title"><span>Phone No.</span></label>
                            <div class="control">
                                <input name="phone_no" id="phone_no" title="phone_no" value="" class="input-text"
                                       type="text"
                                       data-validate="{required:true}">
                            </div>
                        </div>
                        <div class="field required">
                            <label class="label" for="content"><span>Message</span></label>
                            <div class="control">
                                <textarea name="message" id="message" rows="5" cols="8" class="input-text"
                                          data-validate="{required:true}"></textarea>
                            </div>
                        </div>
                    </div>
                </fieldset>
            </fieldset>
            <div class="actions-toolbar">
                <div class="primary">
                    <button type="submit" class="action submit primary" title="Save"><span>Submit</span></button>
                </div>
            </div>
        </form>
    </div>
</div>